server.port=8080
spring.application.name=e-store-backend

# MySQL (base relationnelle)
spring.datasource.url=jdbc:mysql://localhost:3306/estore_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Ziko@2005#Dko
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# Initialisation avec data.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# MongoDB
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=estore_reviews

# Logging
logging.level.com.estore=DEBUG

# D\u00E9sactiver la s\u00E9curit\u00E9 par d\u00E9faut de Spring Security
spring.security.enabled=false